Composition {
	Tools = ordered() {
		MediaIn1 = MediaIn {
			ViewInfo = OperatorInfo { Pos = { 0, 50 } },
		},
		Text1 = TextPlus {
			Inputs = {
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				UseFrameFormatSettings = Input { Value = 1, },
				StyledText = Input { Value = "Text", },
				Font = Input { Value = "Open Sans", },
				Style = Input { Value = "Bold", },
				Size = Input { Value = 0.06, },
				Center = Input { Value = { 0.5, 0.15 }, },
			},
			ViewInfo = OperatorInfo { Pos = { 0, -50 } },
		},
		Merge1 = Merge {
			Inputs = {
				Background = Input { SourceOp = "MediaIn1", Source = "Output", },
				Foreground = Input { SourceOp = "Text1", Source = "Output", },
			},
			ViewInfo = OperatorInfo { Pos = { 150, 50 } },
		},
		MediaOut1 = MediaOut {
			Inputs = {
				Index = Input { Value = "0", },
				Input = Input { SourceOp = "Merge1", Source = "Output", },
			},
			ViewInfo = OperatorInfo { Pos = { 300, 50 } },
		},
	},
}
